prefer_compiled: True # geo functions

asas_dtlookahead: 300 # ASAS lookahead time [sec]
asas_pzr: 5 # ASAS horizontal PZ margin [nm]
asas_pzh: 1000 # ASAS vertical PZ margin [ft]
asas_marh: 1.05 # ASAS protected zone factors - horizontal
asas_marv: 1.05 # ASAS protected zone factors - vertical
