"""Command-line interface for MiniSky."""

import asyncio
import json
import os
import subprocess
from pathlib import Path
from pprint import pprint
from typing import Annotated

import requests
import typer
import websockets
from colorama import Fore, Style
from prompt_toolkit import prompt
from prompt_toolkit.completion import NestedCompleter, PathCompleter
from prompt_toolkit.history import FileHistory

app = typer.Typer(help="MiniSky command-line tools.", no_args_is_help=True)
commands_app = typer.Typer(help="Inspect or regenerate stack-command documentation.")
docs_app = typer.Typer(help="Build or serve the documentation site.")
test_app = typer.Typer(help="Run test suites.")
app.add_typer(commands_app, name="commands")
app.add_typer(docs_app, name="docs")
app.add_typer(test_app, name="test")

history_file = os.path.expanduser("/tmp/hacksky_console_history")
path_completer = PathCompleter()
completer = NestedCompleter.from_nested_dict({"load": path_completer, "/load": path_completer})

COMMAND_DOCS_OUTFILE = Path(__file__).parent.parent / "docs" / "reference" / "commands.md"
COMMAND_DOCS_HEADER = """\
# Stack commands

Every text command understood by the simulator — usable in scenario files, the
[console](../guides/console.md), the REST [`stack/` endpoint](../guides/rest-api.md),
or [`minisky.stack.stack()`](../api/stack.md) from Python. Commands are
case-insensitive.

Argument conventions: optional arguments are enclosed in `[...]`; `callsign` is an
aircraft callsign; `alt` accepts flight levels (`FL100`), feet, or metres; `spd`
accepts CAS in knots or Mach (below 1); `latlon` accepts coordinates or any named
waypoint, navaid, airport, or aircraft.

<!-- This file is generated by `minisky commands docs` — do not edit by hand. -->

| Command | Usage | Description | Synonyms |
| --- | --- | --- | --- |
"""


async def _run_scenario(scenario: str, speed: int) -> None:
    """Initialise the simulator with a scenario and run it to completion."""
    import minisky

    minisky.init(scenario=scenario)
    minisky.load_plugins()
    minisky.runner.speed = speed

    await minisky.runner.run()


@app.command("run")
def run_cmd(
    scenario: Annotated[str, typer.Option(help="Scenario (.scn) file to run.")],
    speed: Annotated[int, typer.Option(help="Simulation speed multiplier.")] = 1,
) -> None:
    """Run a scenario file without interaction."""
    asyncio.run(_run_scenario(scenario, speed))


@app.command("server")
def server_cmd(
    host: Annotated[str, typer.Option(help="Host address to bind.")] = os.environ.get(
        "MINISKY_HOST", "0.0.0.0"
    ),
    port: Annotated[int, typer.Option(help="TCP port to bind.")] = int(
        os.environ.get("MINISKY_PORT", "8000")
    ),
    reload: Annotated[bool, typer.Option(help="Enable uvicorn auto-reload.")] = False,
) -> None:
    """Start the REST and WebSocket API server."""
    import uvicorn

    uvicorn.run("minisky.server:app", host=host, port=port, reload=reload)


@app.command("console")
def console_cmd(
    server: Annotated[str, typer.Option(help="API server base URL.")] = "http://localhost",
    port: Annotated[int, typer.Option(help="API server port.")] = 8000,
) -> None:
    """Run the interactive console client for a MiniSky API server."""
    typer.echo(f"MiniSky Console, connect to {server}:{port}, use /exit to quit")

    root_url = f"{server}:{port}"

    while True:
        print(Fore.LIGHTGREEN_EX + Style.BRIGHT, end="")
        cmd = prompt("> ", completer=completer, history=FileHistory(history_file))
        print(Style.RESET_ALL, end="")

        if cmd == "":
            continue

        if cmd in ("/exit", "exit"):
            break

        if cmd in ("/clear", "clear"):
            os.system("clear")
            continue

        if cmd.startswith("/load ") or cmd.startswith("load "):
            file_path = cmd.split(" ", maxsplit=1)[1]

            if os.path.isfile(file_path):
                with open(file_path, "rb") as f:
                    files = {"file": (os.path.basename(file_path), f)}
                    response = requests.post(f"{root_url}/scn", files=files, timeout=30)
                    typer.echo(response.json())
            else:
                typer.echo("File does not exist\n")
            continue

        if not cmd.startswith("/"):
            response = requests.get(f"{root_url}/stack/{cmd.strip('/')}", timeout=30).json()
            pprint(response)
        else:
            response = requests.get(f"{root_url}/{cmd}", timeout=30).json()
            pprint(response)


async def _stream_snapshots(url: str, raw: bool) -> None:
    async with websockets.connect(url) as ws:
        typer.echo(f"connected to {url}")
        while True:
            snap = json.loads(await ws.recv())
            if raw:
                typer.echo(json.dumps(snap))
                continue
            info = snap["siminfo"]
            ac = snap["acdata"]
            typer.echo(
                f"t={info['simt']:8.1f}s  state={info['state']}  "
                f"ntraf={info['ntraf']}  speed={info['speed']}x  "
                f"callsigns={ac['callsign']}"
            )


@app.command("stream")
def stream_cmd(
    url: Annotated[
        str,
        typer.Option(help="WebSocket URL of the MiniSky stream."),
    ] = "ws://localhost:8000/stream",
    raw: Annotated[bool, typer.Option(help="Print raw JSON snapshots.")] = False,
) -> None:
    """Connect to the streaming API and print snapshots."""
    try:
        asyncio.run(_stream_snapshots(url, raw))
    except KeyboardInterrupt:
        typer.echo("\ndisconnected")


def _build_command_rows() -> list[str]:
    import minisky
    from minisky.stack import Command

    minisky.init()

    primary: dict[str, Command] = {}
    synonyms: dict[str, list[str]] = {}
    for name, cmdobj in sorted(Command.cmddict.items()):
        if cmdobj.name == name:
            primary[name] = cmdobj
        else:
            synonyms.setdefault(cmdobj.name, []).append(name)

    lines: list[str] = []
    for name, cmdobj in sorted(primary.items()):
        usage = (cmdobj.brief or "").replace("|", "\\|").replace("\n", " ")
        help_text = (cmdobj.help or "").replace("|", "\\|")
        help_text = help_text.strip().splitlines()[0] if help_text.strip() else ""
        syns = ", ".join(f"`{s}`" for s in sorted(synonyms.get(name, [])))
        lines.append(f"| `{name}` | `{usage}` | {help_text} | {syns} |\n")
    return lines


@commands_app.command("list")
def commands_list() -> None:
    """Print the stack command table as Markdown."""
    typer.echo(COMMAND_DOCS_HEADER + "".join(_build_command_rows()))


@commands_app.command("docs")
def commands_docs(
    output: Annotated[
        Path,
        typer.Option("--output", "-o", help="Markdown file to write."),
    ] = COMMAND_DOCS_OUTFILE,
) -> None:
    """Regenerate docs/reference/commands.md from the live stack command table."""
    output.parent.mkdir(parents=True, exist_ok=True)
    rows = _build_command_rows()
    output.write_text(COMMAND_DOCS_HEADER + "".join(rows))
    typer.echo(f"Wrote {len(rows)} commands to {output}")


def _run_subprocess(args: list[str]) -> int:
    return subprocess.run(args, check=False).returncode


@app.command("check")
def check_cmd() -> None:
    """Run linting and type checking."""
    for args in (["uv", "run", "ruff", "check", "."], ["uv", "run", "pyright"]):
        code = _run_subprocess(args)
        if code:
            raise typer.Exit(code)


@test_app.command("all")
def test_all() -> None:
    """Run unit and integration tests, excluding API tests."""
    raise typer.Exit(_run_subprocess(["uv", "run", "pytest"]))


@test_app.command("unit")
def test_unit() -> None:
    """Run fast unit tests."""
    raise typer.Exit(_run_subprocess(["uv", "run", "pytest", "tests/unit"]))


@test_app.command("api")
def test_api() -> None:
    """Run opt-in REST API tests."""
    raise typer.Exit(_run_subprocess(["uv", "run", "pytest", "-m", "api", "tests/test_api.py"]))


@docs_app.command("serve")
def docs_serve() -> None:
    """Serve documentation locally with MkDocs."""
    raise typer.Exit(_run_subprocess(["uv", "run", "--group", "docs", "mkdocs", "serve"]))


@docs_app.command("build")
def docs_build() -> None:
    """Build the documentation site with MkDocs."""
    raise typer.Exit(_run_subprocess(["uv", "run", "--group", "docs", "mkdocs", "build"]))
