"""Public contracts for runtime-local MiniSky plugins.

Plugin packages can expose a [Plugin][minisky.plugin.Plugin] value through
the `minisky.plugins` entry-point group.
"""

from __future__ import annotations

from minisky.command import (
    AcId,
    AcIdSelection,
    AltM,
    ArgumentIssue,
    CmdParser,
    CommandCursor,
    CommandField,
    CommandParseContext,
    CoordinateWaypoint,
    FiniteFloat,
    HeadingDeg,
    Keyword,
    LatLonDeg,
    MagneticHdgDeg,
    MagneticHeadingDeg,
    NamedWaypoint,
    NonNegativeFiniteFloat,
    OnOff,
    ParseResult,
    PositiveFiniteFloat,
    RunwayHeadingRequest,
    SimTimeS,
    Spanned,
    SpeedMpsOrMach,
    Text,
    TimeS,
    Token,
    TrueHdgDeg,
    TrueHeadingDeg,
    UseRunwayHeading,
    VspdMps,
    WaypointSpec,
    Wpt,
    command,
)
from minisky.plugin.entity import Entity
from minisky.plugin.plugin import (
    Plugin,
    PluginContext,
    PluginError,
    PluginManager,
    PluginRuntime,
    PluginSpec,
    PluginStatus,
)
from minisky.plugin.plugin_decorators import HookName, hook, replacement

__all__ = (
    "AcId",
    "AcIdSelection",
    "AltM",
    "ArgumentIssue",
    "CmdParser",
    "CommandCursor",
    "CommandField",
    "CommandParseContext",
    "CoordinateWaypoint",
    "Entity",
    "FiniteFloat",
    "HeadingDeg",
    "HookName",
    "Keyword",
    "LatLonDeg",
    "MagneticHdgDeg",
    "MagneticHeadingDeg",
    "NamedWaypoint",
    "NonNegativeFiniteFloat",
    "OnOff",
    "ParseResult",
    "Plugin",
    "PluginContext",
    "PluginError",
    "PluginManager",
    "PluginRuntime",
    "PluginSpec",
    "PluginStatus",
    "PositiveFiniteFloat",
    "RunwayHeadingRequest",
    "SimTimeS",
    "Spanned",
    "SpeedMpsOrMach",
    "Text",
    "TimeS",
    "Token",
    "TrueHdgDeg",
    "TrueHeadingDeg",
    "UseRunwayHeading",
    "VspdMps",
    "WaypointSpec",
    "Wpt",
    "command",
    "hook",
    "replacement",
)
