"""Public contracts for runtime-local MiniSky plugins.

Plugin packages can expose a [Plugin][minisky.plugin.Plugin] value through
the `minisky.plugins` entry-point group.
"""

from __future__ import annotations

from minisky.command import (
    AcId,
    AcIdSelection,
    ArgumentIssue,
    CmdParser,
    CommandCursor,
    CommandField,
    CommandParseContext,
    CoordinateWaypoint,
    DistanceM,
    FiniteFloat,
    HeadingDeg,
    Keyword,
    LatLonDeg,
    NamedWaypoint,
    NonNegativeFiniteFloat,
    OnOff,
    ParseResult,
    PositiveFiniteFloat,
    RunwayHeadingRequest,
    SimTimeS,
    Spanned,
    SpeedMps,
    Text,
    TimeS,
    Token,
    UseRunwayHeading,
    VspdMps,
    WaypointSpec,
    Wpt,
    command,
)
from minisky.plugin.entity import Entity
from minisky.plugin.plugin import (
    Plugin,
    PluginContext,
    PluginError,
    PluginManager,
    PluginRuntime,
    PluginSpec,
    PluginStatus,
)
from minisky.plugin.plugin_decorators import HookName, hook, replacement
from minisky.values import (
    AirspeedKind,
    CasMps,
    GroundTrackDeg,
    LatLonDegrees,
    Mach,
    MagneticHeadingDeg,
    MslAltM,
    StdPressureAltM,
    TrueHeadingDeg,
)

__all__ = (
    "AcId",
    "AcIdSelection",
    "AirspeedKind",
    "ArgumentIssue",
    "CasMps",
    "CmdParser",
    "CommandCursor",
    "CommandField",
    "CommandParseContext",
    "CoordinateWaypoint",
    "DistanceM",
    "Entity",
    "FiniteFloat",
    "GroundTrackDeg",
    "HeadingDeg",
    "HookName",
    "Keyword",
    "LatLonDeg",
    "LatLonDegrees",
    "Mach",
    "MagneticHeadingDeg",
    "MslAltM",
    "NamedWaypoint",
    "NonNegativeFiniteFloat",
    "OnOff",
    "ParseResult",
    "Plugin",
    "PluginContext",
    "PluginError",
    "PluginManager",
    "PluginRuntime",
    "PluginSpec",
    "PluginStatus",
    "PositiveFiniteFloat",
    "RunwayHeadingRequest",
    "SimTimeS",
    "Spanned",
    "SpeedMps",
    "StdPressureAltM",
    "Text",
    "TimeS",
    "Token",
    "TrueHeadingDeg",
    "UseRunwayHeading",
    "VspdMps",
    "WaypointSpec",
    "Wpt",
    "command",
    "hook",
    "replacement",
)
