"""Generate docs/reference/commands.md from the live stack command table.

Initialises the simulator, walks the registered Command objects, and writes a
markdown reference page. Run from the repository root whenever commands change:

    uv run python scripts/gen_command_docs.py
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

import minisky
from minisky.stack import Command

OUTFILE = Path(__file__).parent.parent / "docs" / "reference" / "commands.md"

HEADER = """\
# Stack commands

Every text command understood by the simulator — usable in scenario files, the
[console](../guides/console.md), the REST [`stack/` endpoint](../guides/rest-api.md),
or [`minisky.stack.stack()`](../api/stack.md) from Python. Commands are
case-insensitive.

Argument conventions: optional arguments are enclosed in `[...]`; `callsign` is an
aircraft callsign; `alt` accepts flight levels (`FL100`), feet, or metres; `spd`
accepts CAS in knots or Mach (below 1); `latlon` accepts coordinates or any named
waypoint, navaid, airport, or aircraft.

<!-- This file is generated by scripts/gen_command_docs.py — do not edit by hand. -->

| Command | Usage | Description | Synonyms |
| --- | --- | --- | --- |
"""


def main() -> None:
    minisky.init()

    # cmddict maps every name (including synonyms) to a Command object;
    # group synonyms under the primary name.
    primary: dict[str, Command] = {}
    synonyms: dict[str, list[str]] = {}
    for name, cmdobj in sorted(Command.cmddict.items()):
        if cmdobj.name == name:
            primary[name] = cmdobj
        else:
            synonyms.setdefault(cmdobj.name, []).append(name)

    lines: list[str] = [HEADER]
    for name, cmdobj in sorted(primary.items()):
        usage = (cmdobj.brief or "").replace("|", "\\|").replace("\n", " ")
        help_text = (cmdobj.help or "").replace("|", "\\|")
        # First sentence/line of the help text is enough for the table
        help_text = help_text.strip().splitlines()[0] if help_text.strip() else ""
        syns = ", ".join(f"`{s}`" for s in sorted(synonyms.get(name, [])))
        lines.append(f"| `{name}` | `{usage}` | {help_text} | {syns} |\n")

    OUTFILE.parent.mkdir(parents=True, exist_ok=True)
    OUTFILE.write_text("".join(lines))
    print(f"Wrote {len(primary)} commands to {OUTFILE}")


if __name__ == "__main__":
    main()
