name: ci

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-python:
    name: test python
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10

      - name: Install Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
          cache: pnpm

      - name: Install frontend dependencies
        run: pnpm install --frozen-lockfile

      # NOTE(abraham): we must build the frontend assets otherwise tangram_minisky would fail
      # with missing frontend assets.
      # we should document this and potentially split up the action into repo-with-frontend
      # just like tangram
      - name: Check and build frontend plugin
        run: |
          pnpm check
          pnpm build

      - name: Install uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
        with:
          enable-cache: true

      - name: Install Python dependencies
        run: uv sync --all-groups --all-packages --all-extras

      - name: Check code quality
        run: |
          uv run ruff check packages scripts docs
          uv run ruff format packages scripts docs --check
          uv run pyright

      - name: Run unit and integration tests
        run: uv run pytest

      - name: Run API smoke tests
        run: uv run pytest -m api packages/minisky/tests/test_api.py
