name: ci

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-python:
    name: test python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Install Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: pnpm

      - name: Install frontend dependencies
        run: pnpm install --frozen-lockfile

      # NOTE(abraham): we must build the frontend assets otherwise tangram_minisky would fail
      # with missing frontend assets.
      # we should document this and potentially split up the action into repo-with-frontend
      # just like tangram
      - name: Check and build frontend plugin
        run: |
          pnpm check
          pnpm build

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install Python dependencies
        run: uv sync --all-groups --all-packages

      - name: Check code quality
        run: |
          uv run ruff check packages tests
          uv run ruff format packages tests --check
          uv run pyright

      - name: Run unit and integration tests
        run: uv run pytest

      - name: Run API smoke tests
        run: uv run pytest -m api tests/test_api.py
